# Generated by Django 2.1.7 on 2019-02-26 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progimage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='converted_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progimage.Image'),
        ),
    ]
